# -*- coding: utf-8 -*-
"""VjezbePetak2104.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KaU8RSRFzHYQ8ZoCh0HLbZ26ZxVmlJMU

Provjeriti da li je suma vrijednosti sa glavne dijagonale veca od proizvoda suprotne dijagonale?
"""

matrica = [[1, 2, 3], [4, 2, 7], [6, 8, 4]]

suma = 0
proizvod = 1

for i in range(len(matrica)):
  for j in range(len(matrica[i])):
    if matrica[i] == matrica[j]:
      suma += matrica[i][j]
    elif i + j == len(matrica) - 1:
      proizvod *= matrica[i][j]

if suma > proizvod:
  print("Suma je veca od prozvoda.")
else:
  print("Proizvod je veci od sume.")

"""Zbir najvecih vrijednosti svake vrste"""

def zbir_najvecih_vrijednosti(M):
  zbir_najvecih = 0
  max = 0
  for i in range(0,len(M)):
    for j in range(0,len(M[i])):
      if max<M[i][j]:
        max=M[i][j]
    zbir_najvecih+=max
    max = 0
  return zbir_najvecih

print(zbir_najvecih_vrijednosti(matrica))

"""Matrice - 3 i 4 zadatak"""

def arrange_matrix(dim):
    matix = [[0 for j in range(dim)] for i in range(dim)]
    brojac = 1
    for i in range(dim):
        for j in range(dim):
          if i % 2 != 0:
              matix[dim - j - 1][i] = brojac
          else:
              matix[j][i] = brojac
          brojac += 1
    return matix

print(arrange_matrix(3))

def arrange_matrix_negative(dim):
    matix = [[0 for j in range(dim)] for i in range(dim)]
    brojac = 1
    for i in range(dim):
        for j in range(dim):
          if i % 2 != 0:
              matix[dim - j - 1][i] = -brojac
          else:
              matix[j][i] = brojac
          brojac += 1
    return matix

print(arrange_matrix_negative(4))

"""Matrice - Zadatak 5"""

def parking_mjesta(matrica):
  mjesta = 0
  for row in matrica:
    for i in range(len(row)-1):
      if row[i] == 0 and row[i + 1] == 0:
        mjesta += 1
        row[i], row[i+1] = 1,1
  return mjesta

  matrica= [[0,0,1,1], [0,0,0,0], [1,1,0,0]]
  print(parking_mjesta(matrica))

"""Matrice- Zadatak 7"""

def kvadratna(A):
  num_red = len(A)
  for row in A:
    if len(row) != num_red:
      return False
  return True

matrica1= [[12,3,2], [12,3,4]]
matrica2= [[12,2], [12,3]]

print(kvadratna(matrica1))
print(kvadratna(matrica2))

"""Matrice - Zadatak 8"""

def substract(A,B):
  C = []
  for i in range(0,len(A)):
    row = []
    for j in range(0,len(A[0])):
      row.append(0)
    C.append(row)

  for i in range(0,len(C)):
    for j in range(0,len(C[i])):
      C[i][j]=A[i][j]-B[i][j]
  return C

matrica1= [[12,3,2], [10,1,2]]
matrica2= [[12,3,5], [9,2,4]]

print(substract(matrica1,matrica2))